{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- toYaml .Values.serviceAccount.role | nindent 4 }}
  name: {{ .Values.serviceAccount.name }}
{{- end }}