FROM apache/airflow:2.7.3

USER root

# Install OpenJDK-11
RUN apt update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get install -y screen && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

# Set AIRFLOW_HOME
ENV AIRFLOW_HOME=/opt/airflow

USER airflow
# Install Dependecies
RUN pip install snowflake-ingest==1.0.5
RUN pip install ocean-spark-airflow-provider==0.1.3
RUN pip install simplejson==3.18.0
RUN pip install pyspark==3.3.1
RUN pip install stringcase==1.2.0
RUN pip install apache-airflow-providers-slack==7.0.0
RUN pip install snowflake-sqlalchemy==1.5.0
RUN pip install pandas==1.5.3